# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/pacers31colts18"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bluesky"
name = "BlueSky"
url = "https://bsky.app/profile/joeloveless.com"

[social.params]
icon = "brand-bluesky"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://infosec.exchange/@Pacers31Colts18"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "linkedin"
name = "linkedin"
url = "https://www.linkedin.com/in/joe-loveless/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "email"
name = "email"
url = "mailto:joe@joeloveless.com"

[social.params]
icon = "mail"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"